spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vinylstore
    username: your_user
    password: your_password
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: your_brevo_user
    password: your_brevo_api_key
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

api:
  file-metadata:
    endpoint: '/api/v1/files/{id}'